# Major Montana landowners FINAL analysis

In [1]:
# Library import and config
import json
import pandas as pd
import geopandas as gpd
pd.set_option('display.max_rows', 100) # Avoids truncation of long data table results
pd.set_option('display.max_columns', 100) # Avoids truncation of wide data table results

In [2]:
# Read in data (slow)
# Parcel data from **March 9** download -- may need to update file path
parcels = gpd.read_file('./raw/MontanaCadastral_SHP_3-9-2026/Montana_Cadastral/OWNERPARCEL.shp').to_crs(epsg=4326)

In [3]:
# Add in ownership groupings

with open('./owner-name-grouping.json', 'r') as file:
    OWNER_GROUPS_RAW = json.load(file)

cleaner = {}
for group in OWNER_GROUPS_RAW:
    ownerCleaned = group['owner']
    for ownerAlternate in group['alternatesOwnershipNames']:
        cleaner[ownerAlternate] = ownerCleaned
parcels['OwnerName_Grouped'] = parcels['OwnerName'].replace(cleaner)

In [5]:
# Group parcels by owner name, count the number in each group and sum by acreage in each group
# Running more than top 10 here because most of the biggest are public entities, which we need to filter out
top_100_landowners = parcels.groupby(['OwnerName_Grouped']).agg({
    'PARCELID': 'count',
    'TotalAcres': 'sum',
    'OwnerName': 'unique',
}).sort_values('TotalAcres', ascending=False).head(100)

top_100_landowners.head(10) # Show top 10 to check output

,PARCELID,TotalAcres,OwnerName
OwnerName_Grouped,,,
USDA FOREST SERVICE,16672,8775511.897,[USDA FOREST SERVICE]
USDI BUREAU OF LAND MANAGEMENT,18102,5604489.400,[USDI BUREAU OF LAND MANAGEMENT]
STATE OF MONTANA,12223,4265228.436,[STATE OF MONTANA]
UNITED STATES OF AMERICA,5580,1881103.943,[UNITED STATES OF AMERICA]
USA,3985,1828458.927,[USA]
USA IN TRUST FOR CROW TRIBE,3848,1303624.520,[USA IN TRUST FOR CROW TRIBE]
USA IN TRUST,5279,1139955.995,[USA IN TRUST]
USA - FOREST SERVICE,2161,1115836.824,[USA - FOREST SERVICE]
BUREAU OF LAND MANAGEMENT,2735,732067.380,[BUREAU OF LAND MANAGEMENT]
USDI FISH AND WILDLIFE SERVICE,1252,578523.512,[USDI FISH AND WILDLIFE SERVICE]

In [6]:
# Filter out manually identified public landowners

with open('./known-public-landowners.json', 'r') as file:
    PUBLIC_LANDOWNERS = json.load(file)

top_100_private_only = top_100_landowners[~top_100_landowners.index.isin(PUBLIC_LANDOWNERS)]

# Add rank for display purposes
ranking = top_100_private_only.copy().reset_index()
ranking['Rank'] = ranking.index+1
ranking.rename(columns={
    'PARCELID': 'NumParcels',
    'OwnerName_Grouped': 'Owner',
    'OwnerName': 'IncludedOwnerNames',
    }, inplace=True)
ranking.head(30)[['Rank','Owner','NumParcels','TotalAcres',]] # show top 20

    Rank                           Owner  NumParcels  TotalAcres
0      1                      GALT RANCH         820  346571.264
1      2            FARMLAND RESERVE INC         653  316931.462
2      3   BROKEN O LAND & LIVESTOCK LLC         780  291870.037
3      4  GREEN DIAMOND RESOURCE COMPANY         644  291802.938
4      5                  WILKS BROTHERS         705  275634.288
5      6                    COFFEE-NEFSY         503  238831.067
6      7          SUNLIGHT RANCH COMPANY         713  236713.603
7      8                AMERICAN PRAIRIE         606  145969.964
8      9              NATURE CONSERVANCY         389  142986.131
9     10       GREAT NORTHERN PROPERTIES         292  142849.817
10    11               STIMSON LUMBER CO         389  129176.561
11    12                     N5B CAPITAL         324  126531.610
12    13                 SPP MONTANA LLC         327  121476.997
13    14                HILLENBRAND JOHN         285  117724.130
14    15                      TED TURNER         235  115278.127
15    16   BEAVERHEAD RANCH PROPERTY LLC         406  113049.411
16    17               HEAL HOLDINGS LLC         307   96156.753
17    18           CHERRY CREEK SHEEP CO         206   95501.110
18    19           PADLOCK RANCH COMPANY         337   91720.720
19    20                MONTGOMERY RANCH         168   86802.953
20    21           CROSS FOUR CATTLE LLC         176   85088.249
21    22                 SIEBEN RANCH CO         198   74010.494
22    23               DUTTON RANCH, INC         142   73110.993
23    24                 SINGLETON FARMS         124   69978.140
24    25          BOOTH LAND & LIVESTOCK         148   67031.231
25    26              DEARBORN RANCH LLC         165   65892.007
26    27            IX RANCH COMPANY LLC         185   65849.890
27    28            SAND CREEK RANCH LLC         228   62078.861
28    29        CA MT ACQUISITION CO LLC         126   61696.887
29    30          FROZE TO DEATH LAND CO         117   54113.520

In [7]:
# Write top 20 list to outputs file as JSON
ranking.head(20).to_json('./outputs/final-top-20-list.json', orient='records', indent=4, index=False)

In [8]:
# More human-readable listing with acreages for each underlying owner name
# Manually copy and paste to outputs/
    

for idx, row in ranking.head(20).iterrows():
    print('#' + str(idx+1) + ' / ' + row['Owner'])
    print(f'{row['TotalAcres']:,.0f} acres - {str(row['NumParcels'])} parcels')
    print('  Includes:')
    for subOwner in row['IncludedOwnerNames']:
        subOwnerParcels = parcels[parcels['OwnerName'] == subOwner]
        print(f'    {subOwner} --> {subOwnerParcels['TotalAcres'].sum():,.0f} acres/ {len(subOwnerParcels)} parcels')
    print('\n')

#1 / GALT RANCH
346,571 acres - 820 parcels
  Includes:
    SUN COULEE LLC --> 4,508 acres/ 20 parcels
    71 RANCH LP --> 249,141 acres/ 616 parcels
    GALT RANCH LP --> 92,922 acres/ 182 parcels
    GALT ERROL T --> 1 acres/ 1 parcels
    GALT ERROL T & SHARRIE K --> 0 acres/ 1 parcels


#2 / FARMLAND RESERVE INC
316,931 acres - 653 parcels
  Includes:
    FARMLAND RESERVE, INC --> 18,197 acres/ 30 parcels
    FARMLAND RESERVE INC --> 298,535 acres/ 621 parcels
    FARMLAND RESERVES INC --> 200 acres/ 2 parcels


#3 / BROKEN O LAND & LIVESTOCK LLC
291,870 acres - 780 parcels
  Includes:
    PV RANCH COMPANY LLC --> 116,672 acres/ 212 parcels
    PV RANCH CO LLC --> 16,312 acres/ 32 parcels
    FORT PEASE COMM PASTURE --> 20,847 acres/ 41 parcels
    BROKEN O LAND & LIVESTOCK LLC --> 119,111 acres/ 454 parcels
    KROENKE LAND & LIVESTOCK LLC --> 12,485 acres/ 25 parcels
    KROENKE LAND & LIVESTOCK CO LLC --> 3,332 acres/ 10 parcels
    KROENKE LAND & LIVESTOCK --> 651 acres/ 2 parcels
    KROENKE LAND & LIVESTOCK COMPANY LLC --> 539 acres/ 1 parcels
    FORT PEASE COMMUNITY PASTURE INC --> 1,280 acres/ 2 parcels
    FORT PEASE COMMUNITY PASTURE, INC --> 640 acres/ 1 parcels


#4 / GREEN DIAMOND RESOURCE COMPANY
291,803 acres - 644 parcels
  Includes:
    GREEN DIAMOND RESOURCE COMPANY --> 291,803 acres/ 644 parcels


#5 / WILKS BROTHERS
275,634 acres - 705 parcels
  Includes:
    WILKS RANCH MONTANA LTD --> 271,093 acres/ 690 parcels
    WILKS RANCH MONTANA LTD A TEXAS DOMESTIC LIMITED PARTNERSHIP --> 1,546 acres/ 3 parcels
    WILKS JOANN --> 720 acres/ 3 parcels
    WILKS STACI --> 760 acres/ 4 parcels
    WILKS FARRIS --> 766 acres/ 3 parcels
    WILKS DAN --> 749 acres/ 2 parcels


#6 / COFFEE-NEFSY
238,831 acres - 503 parcels
  Includes:
    COFFEE NEFSY LIMITED PARTNERSHIP --> 152,762 acres/ 322 parcels
    COFFEE-NEFSY LIMITED PARTNERSHIP --> 4,119 acres/ 7 parcels
    COFFEE-NEFSY LP --> 33,758 acres/ 71 parcels
    COFFEE CATTLE COMPANY --> 47 acres/ 2 parcels
    COFFEE VIRGINIA NEFSY --> 1 acres/ 1 parcels
    COFFEE RANCH LLC --> 48,144 acres/ 97 parcels
    COFFEE VIRGINIA N --> 0 acres/ 1 parcels
    COFFEE VIRGINIA A --> 1 acres/ 1 parcels
    COFFEE, VIRGINIA A & CAREN L --> 0 acres/ 1 parcels


#7 / SUNLIGHT RANCH COMPANY
236,714 acres - 713 parcels
  Includes:
    SUNLIGHT RANCH COMPANY --> 235,991 acres/ 706 parcels
    SUNLIGHT RANCH COMPANY A WYOMING CORPORATION --> 2 acres/ 1 parcels
    SUNLIGHT RANCH COMPANY INC --> 720 acres/ 6 parcels


#8 / AMERICAN PRAIRIE
145,970 acres - 606 parcels
  Includes:
    AMERICAN PRAIRIE FOUNDATION --> 143,649 acres/ 592 parcels
    5 MOUNTAIN RANCH LLC --> 2,321 acres/ 14 parcels


#9 / NATURE CONSERVANCY
142,986 acres - 389 parcels
  Includes:
    NATURE CONSERVANCY --> 13,074 acres/ 41 parcels
    NATURE CONSERVANCY THE --> 10,464 acres/ 66 parcels
    THE NATURE CONSERVANCY --> 34,722 acres/ 93 parcels
    NATURE CONSERVANCY (THE) --> 3,486 acres/ 9 parcels
    MONTANA CHECKERBOARD LLC --> 81,241 acres/ 180 parcels


#10 / GREAT NORTHERN PROPERTIES
142,850 acres - 292 parcels
  Includes:
    GREAT NORTHERN PROPERTIES --> 18,670 acres/ 42 parcels
    GREAT NORTHERN PROPERTIES LP --> 81,111 acres/ 148 parcels
    GREAT NORTHERN PROP LTD PTNSH --> 30,681 acres/ 62 parcels
    GREAT NORTHERN PROPERTIES LIMITED PARTNERSHIP --> 6,559 acres/ 14 parcels
    GREAT NORTHERN PROPERTIES LTD PTNSHP --> 2,738 acres/ 17 parcels
    GREAT NORTHERN PROPERTIES LMTD PTNSHP --> 50 acres/ 1 parcels
    GREAT NORTHERN PROPERTIES LTD PTNSH --> 640 acres/ 1 parcels
    GREAT NORTHERN PROPERTIES LTD PNTSHP --> 240 acres/ 1 parcels
    GREAT NORTHERN PROPERTY LTD PTNSHP --> 240 acres/ 2 parcels
    GREAT NTHRN PROP LTD PRTNRSHP --> 1,920 acres/ 4 parcels


#11 / STIMSON LUMBER CO
129,177 acres - 389 parcels
  Includes:
    STIMSON LUMBER CO --> 118,741 acres/ 325 parcels
    STIMSON LUMBER COMPANY --> 9,682 acres/ 61 parcels
    STIMSON LUMBER --> 60 acres/ 1 parcels
    STIMSOM LUMBER COMPANY --> 694 acres/ 2 parcels


#12 / N5B CAPITAL
126,532 acres - 324 parcels
  Includes:
    FLATHEAD RIDGE RANCH LLC --> 22,644 acres/ 69 parcels
    FRR HUBBARD LLC --> 17,493 acres/ 36 parcels
    FRR MURR PEAK LLC --> 16,860 acres/ 42 parcels
    FRR BROWNS MEADOW LLC --> 17,491 acres/ 40 parcels
    FRR LOST PRAIRIE LLC --> 17,492 acres/ 44 parcels
    FRR SICKLER CREEK LLC --> 16,849 acres/ 39 parcels
    FRR RODGERS LAKE LLC --> 17,451 acres/ 45 parcels
    LOOKOUT RIDGE LLC --> 250 acres/ 9 parcels


#13 / SPP MONTANA LLC
121,477 acres - 327 parcels
  Includes:
    SPP MONTANA LLC --> 116,398 acres/ 305 parcels
    ELBERTON TIMBERLANDS LLC --> 922 acres/ 2 parcels
    HW GULCH HOLDINGS LLC --> 610 acres/ 2 parcels
    PATTON PATRICK C --> 3,547 acres/ 17 parcels
    TREESAP LLC --> 0 acres/ 1 parcels


#14 / HILLENBRAND JOHN
117,724 acres - 285 parcels
  Includes:
    HILLENBRAND JOHN --> 117,724 acres/ 285 parcels


#15 / TED TURNER
115,278 acres - 235 parcels
  Includes:
    TURNER MONTANA PROPERTIES LLC --> 76,035 acres/ 147 parcels
    TURNER ENTERPRISES INC --> 39,120 acres/ 86 parcels
    TURNER LAND HOLDINGS LLC --> 122 acres/ 1 parcels
    TURNER MANAGEMENT ENTERPRISES LLC --> 0 acres/ 1 parcels


#16 / BEAVERHEAD RANCH PROPERTY LLC
113,049 acres - 406 parcels
  Includes:
    BEAVERHEAD RANCH PROPERTY LLC --> 113,049 acres/ 406 parcels


#17 / HEAL HOLDINGS LLC
96,157 acres - 307 parcels
  Includes:
    HEAL HOLDINGS LLC --> 96,157 acres/ 307 parcels


#18 / CHERRY CREEK SHEEP CO
95,501 acres - 206 parcels
  Includes:
    CHERRY CREEK SHEEP CO --> 59,477 acres/ 111 parcels
    JT BREWER LLC --> 31,643 acres/ 77 parcels
    BREWER JASON --> 320 acres/ 1 parcels
    BREWER JASON & TANYA --> 2,295 acres/ 7 parcels
    BREWER JASON T & TANYA J --> 1,441 acres/ 7 parcels
    BREWER JASON T & TANYA JEAN --> 10 acres/ 1 parcels
    CHERRY CREEK SHEEP CO INC --> 160 acres/ 1 parcels
    BREWER JASON & TANYA J --> 156 acres/ 1 parcels


#19 / PADLOCK RANCH COMPANY
91,721 acres - 337 parcels
  Includes:
    PADLOCK RANCH CO --> 41,176 acres/ 174 parcels
    SCOTT LAND & LIVESTOCK LTD PARTNERSHIP --> 6,364 acres/ 36 parcels
    PADLOCK RANCH COMPANY --> 8,739 acres/ 32 parcels
    PADLOCK RANCH CO INC --> 35,122 acres/ 92 parcels
    FIRST INTERSTATE BANK OF SHERIDAN CONS --> 320 acres/ 3 parcels


#20 / MONTGOMERY RANCH
86,803 acres - 168 parcels
  Includes:
    MONTGOMERY RANCH --> 80 acres/ 1 parcels
    MONTGOMERY RANCH CO --> 71,671 acres/ 141 parcels
    MONTGOMERY RANCH COMPANY --> 14,820 acres/ 25 parcels
    BETHKE CAMERON --> 232 acres/ 1 parcels

In [ ]:
# # Write parcels to separate file to allow analysis using MTFP-assigned groupings in explore.ipyb
parcels.to_file('./cleaned/parcels-with-mtfp-groupings.shp')

In [26]:
# Export geojson data for the parcels owned by each of the top 20 landowners 
majorColumns = ['CountyName','OwnerName_Grouped','OwnerName','OwnerAddre','OwnerAdd_1','OwnerAdd_2','OwnerCity','OwnerState','PropType','TotalAcres','geometry']
for idx, row in ranking.head(20).iterrows():
    subOwnerParcels = parcels[parcels['OwnerName_Grouped'] == row['Owner']][majorColumns]
    path = f'./geodata-outputs/{str(idx+1)}-{row['Owner'].replace(' ','-').replace('&-','')}.geojson'
    subOwnerParcels.to_file(path, driver="GeoJSON")